# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df234b4b2009c53259f9a515574134c473309a697cad7440d70557eaebdfa8ef9618e70834dfa5c4bc791b1ace6f3acab9cf323b56c70e277273296c8c192bba

test:
  secret_key_base: 9efceaebe644fb6a9a85da91b64626f3900b05be4ec9f093449e69445c55f34cdbd3f07ffd8023a00fa7751922e59828797b99eea36c56d585f202f751653e42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
